# Generated by Django 6.0.5 on 2026-05-18 09:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='cv'),
        ),
    ]
